language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
branches:
  only:
    - master
    - /^release-.+$/
script: >
  mvn test \
   -Dteavm.junit.target=target/js-tests \
   -Dteavm.junit.js.runner=htmlunit \
   -Dteavm.junit.js.threads=2
after_script:
  - rm -rf $HOME/.m2/repository/org/teavm