language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
after_script:
  - rm -rf $HOME/.m2/repository/org/teavm
script:
  - mvn test \
  -   -Pteavm.test.skip=false \
  -   -Pteavm.test.selenium="http://$SAUCE_USER_NAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub" \
  -   -Pteavm.test.threads=2